Remove semicolon from tiny43 variant's digitalPinToPCMSKbit() macro
This caused compilation failures:

/home/travis/Arduino/hardware/ATTinyCore/avr/variants/tiny43/pins_arduino.h:149:43: error: expected ')' before ';' token
 #define digitalPinToPCMSKbit(p) ((p)&0x07);
                                           ^
/home/travis/Arduino/hardware/ATTinyCore/avr/libraries/SoftwareSerial/SoftwareSerial.cpp:362:28: note: in expansion of macro 'digitalPinToPCMSKbit'
     _pcint_maskvalue = _BV(digitalPinToPCMSKbit(_receivePin));
                            ^