Add missing yield function prototypes
Missing function prototypes for yield() in the cores caused compilation to fail for any code that called this function:

error: 'yield' was not declared in this scope